name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'linewebhookapp-seq' }}
  IMAGE_NAME: ${{ 'linewebhook-seq' }}
  LINE_NOTIFY: ${{ secrets.LINE_NOTIFY_BEARER_TOKEN }}

jobs:

  heroku-setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup date as env variable
        run: echo "NOW=$(date +'%Y/%m/%d %H:%M')" >> $GITHUB_ENV
      
      - name: Setup top commit message as env variable
        run: echo "TOP_COMMIT_MESSAGE=$(git log --pretty=format:"%s" -1)" >> $GITHUB_ENV

      - name: Docker configuration
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Heroku push image
        run: heroku container:push $IMAGE_NAME -a $APP_NAME

      - name: Heroku release image
        run: heroku container:release $IMAGE_NAME -a $APP_NAME
      